import { createContext, useContext, type ReactNode } from "react";
import type { AIVoice, PersonaOverride } from "./types";
import { personaWithOverride, type Persona } from "./personas";

/**
 * Lightweight React context that carries the per-game persona overrides
 * (generated by the LLM at game start, see `RiskRobinGame.tsx`).
 *
 * The override includes name, role, location, and bio — so every session
 * surfaces a different cross-section of Edinburgh residents (e.g. a student,
 * a musician, an unemployed parent), not just renamed defaults.
 *
 * Components that render persona info should call `useResolvedPersona(voice)`
 * instead of importing `personaFor` directly — that way they automatically
 * pick up the per-game persona without having to plumb props through every
 * intermediate layer.
 */

export type PersonaNameOverrideMap = Record<AIVoice, PersonaOverride> | null;

const PersonaNamesContext = createContext<PersonaNameOverrideMap>(null);

export function PersonaNamesProvider({
  overrides,
  children,
}: {
  overrides: PersonaNameOverrideMap;
  children: ReactNode;
}) {
  return (
    <PersonaNamesContext.Provider value={overrides}>
      {children}
    </PersonaNamesContext.Provider>
  );
}

/** Resolve a persona for a voice, applying the current per-game name override. */
export function useResolvedPersona(
  voice: AIVoice | string
): Persona | undefined {
  const overrides = useContext(PersonaNamesContext);
  return personaWithOverride(voice, overrides ?? undefined);
}

/** Returns the active override map (null if names haven't been generated yet). */
export function usePersonaOverrides(): PersonaNameOverrideMap {
  return useContext(PersonaNamesContext);
}
